export enum Permissao {
  GERENCIAR_BASE_DADOS = 'GERENCIAR_BASE_DADOS',
  GERENCIAR_VISUALIZACOES = 'GERENCIAR_VISUALIZACOES',
  GERENCIAR_CAMPANHAS = 'GERENCIAR_CAMPANHAS',
  GERENCIAR_INTEGRACOES = 'GERENCIAR_INTEGRACOES',
}
