export enum Permissao {
  EDITAR_BASE_DADOS = 'EDITAR_BASE_DADOS',
  VISUALIZAR_RELATORIOS = 'VISUALIZAR_RELATORIOS',
  EDITAR_CAMPANHAS = 'EDITAR_CAMPANHAS',
  EDITAR_INTEGRACOES = 'EDITAR_INTEGRACOES',
}
