import { STATUS_CAMPANHA } from './types/campanha.type';

export const CLIENTES_CAMPANHA_BATCH_SIZE = 100;
export const POPULA_CLIENTES_CAMPANHA_BATCH_SIZE = 500;
export const CAMPO_REFERENCIA_PREFIX = '#';

export const TRANSICOES_STATUS_CAMPANHA: ReadonlyMap<
  STATUS_CAMPANHA,
  readonly STATUS_CAMPANHA[]
> = new Map([
  [
    STATUS_CAMPANHA.EM_ENVIO,
    [STATUS_CAMPANHA.PAUSA, STATUS_CAMPANHA.CANCELADO],
  ],
  [STATUS_CAMPANHA.PAUSA, [STATUS_CAMPANHA.EM_ENVIO]],
]);
