export enum TipoCampo {
  TEXTO = 'TEXTO',
  NUMERO = 'NUMERO',
  BOOLEANO = 'BOOLEANO',
  UTC = 'UTC',
  MM_DD_YYYY = 'MM_DD_YYYY',
  DD_MM_YYYY = 'DD_MM_YYYY',
  YYYY_MM_DD = 'YYYY_MM_DD',
  EMAIL = 'EMAIL',
  TELEFONE = 'TELEFONE',
}
